version:  '3'

services:

  nginx:
    container_name: nginx
    build:  ./requirements/nginx
    image:  nginx
    ports:
      - '443:443'
    volumes:
      - vol_wp:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - incepnet
    restart:  always

  wordpress:
    container_name: wordpress
    build:  ./requirements/wordpress
    image:  wordpress
    volumes:
      - vol_wp:/var/www/wordpress
    env_file:
      - ./.env
    depends_on:
      - mariadb
    networks:
      - incepnet
    restart:  always

  mariadb:
    container_name: mariadb 
    build:  ./requirements/mariadb
    image:  mariadb
    volumes:
      - vol_mdb
    env_file:
      - ./.env
    networks:
      - incepnet
    restart:  always

volumes:
  vol_wp:
    driver: local
    driver_opts:
      type: none
      device: /home/ntamayo-/data/vol_wp
      o:  bind

  vol_mdb:
    driver: local
    driver_opts:
      type: none
      device: /home/ntamayo-/data/vol_mdb
      o:  bind

networks:
  incepnet: {}
